# Generated by Django 4.1.11 on 2024-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
