# Generated by Django 4.1.11 on 2024-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp_app', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='acknowledge',
            field=models.BooleanField(default=False),
        ),
    ]
