# Generated by Django 4.1.11 on 2024-03-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp_app', '0004_application_acknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
